global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: bridgeworks-public
    metrics_path: /metrics
    static_configs:
      - targets: ["public-4y3o:10000"]
  - job_name: bridgeworks-staff
    metrics_path: /metrics
    static_configs:
      - targets: ["staff-4glx:10000"]
  - job_name: bridgeworks-user
    metrics_path: /metrics
    static_configs:
      - targets: ["bridgeworks-pm:10000"]
  - job_name: bridgeworks-api
    metrics_path: /metrics
    static_configs:
      - targets: ["bridgeworks-pm-t722:10000"]
  - job_name: bridgeworks-org
    metrics_path: /metrics
    static_configs:
      - targets: ["org-hf3s:10000"]
  - job_name: bridgeworks-console
    metrics_path: /metrics
    static_configs:
      - targets: ["console-tjea:10000"]
